/**
 * StockTrace — Case Engine
 * Manages the complete lifecycle and state transitions of StockTrace investigations.
 * 
 * Lifecycle:
 * FAILED_PICK
 *  -> INVESTIGATING
 *  -> RECOMMENDATION_READY
 *  -> AWAITING_VERIFICATION
 *  -> FOUND | NOT_FOUND | PARTIALLY_FOUND | WRONG_QUANTITY | DAMAGED | ESCALATED
 */

import {
  HarnessCaseModel,
  CaseStatus,
  CaseAuditEvent,
  WorkerVerificationOutcome,
  DiscrepancyRecord,
  ScannerEvidence,
  CameraEvidenceEvent,
} from './types';
import { normalizeEvidenceCollection, RawScannerInput, RawCameraInput } from './evidence_normalizer';
import { fuseEvidence, FusedEvidenceReport } from './evidence_fusion';
import { evaluateCandidates, CandidateEvaluationResult } from './candidate_engine';
import { applyGuardrails, processVerificationOutcome } from './guardrails';
import { generateGroundedExplanation, GroundedExplanationResult } from './explanation_engine';

export type UserRole = 'OPERATOR' | 'SUPERVISOR' | 'SYSTEM';

export interface InvestigationExecutionResult {
  caseModel: HarnessCaseModel;
  evaluation: CandidateEvaluationResult;
  fusedReport: FusedEvidenceReport;
  explanation: GroundedExplanationResult;
}

export class StockTraceCaseEngine {
  private cases: Map<string, HarnessCaseModel> = new Map();
  private auditTrails: Map<string, CaseAuditEvent[]> = new Map();
  private discrepancies: DiscrepancyRecord[] = [];

  constructor(initialCases?: HarnessCaseModel[]) {
    if (initialCases) {
      for (const c of initialCases) {
        this.registerCase(c);
      }
    }
  }

  /**
   * Registers a new or existing failed-pick case into the engine.
   */
  public registerCase(caseInput: Partial<HarnessCaseModel> & { case_id: string; sku: string }): HarnessCaseModel {
    const existing = this.cases.get(caseInput.case_id);
    if (existing) {
      return existing;
    }

    const now = new Date().toISOString();
    const newCase: HarnessCaseModel = {
      case_id: caseInput.case_id,
      sku: caseInput.sku,
      item_name: caseInput.item_name || 'Warehouse Inventory Item',
      expected_location: caseInput.expected_location || 'A12',
      expected_quantity: caseInput.expected_quantity || 1,
      failed_at: caseInput.failed_at || now,
      status: 'FAILED_PICK',
      scanner_evidence: caseInput.scanner_evidence || [],
      camera_evidence: caseInput.camera_evidence || [],
      candidate_locations: caseInput.candidate_locations || [],
      created_at: now,
      updated_at: now,
    };

    this.cases.set(newCase.case_id, newCase);
    this.recordAudit(newCase.case_id, 'FAILED_PICK', 'REGISTER_CASE', 'System', {
      sku: newCase.sku,
      expected_location: newCase.expected_location,
    });

    return newCase;
  }

  /**
   * Retrieves a case by ID.
   */
  public getCase(caseId: string): HarnessCaseModel | undefined {
    return this.cases.get(caseId);
  }

  /**
   * Retrieves all registered cases.
   */
  public getAllCases(): HarnessCaseModel[] {
    return Array.from(this.cases.values());
  }

  /**
   * Retrieves audit logs for a case.
   */
  public getAuditTrail(caseId: string): CaseAuditEvent[] {
    return this.auditTrails.get(caseId) || [];
  }

  /**
   * Retrieves all discrepancy records generated by verification results.
   */
  public getDiscrepancies(): DiscrepancyRecord[] {
    return this.discrepancies;
  }

  /**
   * Starts an automated investigation:
   * 1. Transitions case to INVESTIGATING
   * 2. Normalizes scanner and camera evidence
   * 3. Fuses evidence into unified report
   * 4. Ranks candidate locations
   * 5. Enforces safety guardrails
   * 6. Transitions case to RECOMMENDATION_READY or ESCALATED
   */
  public runInvestigation(
    caseId: string,
    scannerRecords: (RawScannerInput | ScannerEvidence)[],
    cameraRecords: (RawCameraInput | CameraEvidenceEvent)[],
    options?: {
      forceScenario?: 'happy-path' | 'conflict' | 'no-camera';
      isStale?: boolean;
      referenceNow?: Date | number | string;
    }
  ): InvestigationExecutionResult {
    const c = this.cases.get(caseId);
    if (!c) {
      throw new Error(`Case ${caseId} not found in StockTrace engine.`);
    }

    // Step A: Transition to INVESTIGATING
    this.transitionStatus(c, 'INVESTIGATING', 'START_INVESTIGATION', 'Picker');

    // Step B: Normalize Evidence
    const normalized = normalizeEvidenceCollection(scannerRecords, cameraRecords);

    // Step C: Evidence Fusion
    const fusedReport = fuseEvidence(c.sku, c.expected_location, normalized, options);

    // Step D: Candidate Evaluation & Ranking
    const rawEvaluation = evaluateCandidates(fusedReport, c.expected_quantity, { referenceNow: options?.referenceNow });

    // Step E: Apply Guardrails
    const guardrailResult = applyGuardrails(rawEvaluation, normalized);
    const evaluation = guardrailResult.sanitizedEvaluation;

    // Step F: Update Case State
    c.candidate_locations = evaluation.candidates;
    c.recommendation = evaluation.recommendationDisplay;
    c.recommendation_reason = evaluation.whyRationale;
    c.confidence_state = evaluation.confidenceState;
    c.updated_at = new Date().toISOString();

    if (evaluation.hasWinningCandidate) {
      this.transitionStatus(c, 'RECOMMENDATION_READY', 'PRODUCE_RECOMMENDATION', 'Engine', {
        recommendation: evaluation.recommendationDisplay,
        confidence: evaluation.confidenceState,
      });
      // Immediately await picker physical confirmation
      this.transitionStatus(c, 'AWAITING_VERIFICATION', 'AWAIT_WORKER_VERIFICATION', 'Engine');
    } else {
      this.transitionStatus(c, 'ESCALATED', 'ESCALATE_NO_WINNER', 'Engine', {
        reason: evaluation.refusalReason || 'No winning candidate',
      });
    }

    // Step G: Generate Grounded Operator Explanation
    const explanation = generateGroundedExplanation({
      fusedReport,
      evaluation,
    });

    return {
      caseModel: c,
      evaluation,
      fusedReport,
      explanation,
    };
  }

  /**
   * Accepts worker physical verification outcome and records final status.
   */
  public recordWorkerVerification(params: {
    caseId: string;
    outcome: WorkerVerificationOutcome;
    verifiedLocation?: string;
    actualQuantity?: number;
    notes?: string;
    role?: UserRole;
  }): {
    caseModel: HarnessCaseModel;
    discrepancy?: DiscrepancyRecord;
  } {
    const c = this.cases.get(params.caseId);
    if (!c) {
      throw new Error(`Case ${params.caseId} not found in StockTrace engine.`);
    }

    const verificationResult = processVerificationOutcome({
      caseId: c.case_id,
      sku: c.sku,
      expectedLocation: c.expected_location,
      recommendedLocation: params.verifiedLocation || c.recommendation,
      expectedQuantity: c.expected_quantity,
      actualQuantity: params.actualQuantity,
      outcome: params.outcome,
      notes: params.notes,
    });

    c.worker_verification = params.outcome;
    c.found_quantity = params.actualQuantity ?? (params.outcome === 'FOUND' ? c.expected_quantity : 0);
    c.outcome = verificationResult.auditMessage;
    c.updated_at = new Date().toISOString();

    // Set terminal status
    const terminalStatus: CaseStatus =
      params.outcome === 'FOUND'
        ? 'FOUND'
        : params.outcome === 'NOT_FOUND'
        ? 'NOT_FOUND'
        : params.outcome === 'WRONG_QUANTITY'
        ? 'WRONG_QUANTITY'
        : params.outcome === 'PARTIALLY_FOUND'
        ? 'PARTIALLY_FOUND'
        : params.outcome === 'DAMAGED'
        ? 'DAMAGED'
        : 'ESCALATED';

    this.transitionStatus(c, terminalStatus, 'WORKER_VERIFICATION', 'Picker', {
      outcome: params.outcome,
      verifiedLocation: params.verifiedLocation,
      actualQuantity: params.actualQuantity,
    });

    if (verificationResult.discrepancyRecord) {
      this.discrepancies.push(verificationResult.discrepancyRecord);
    }

    return {
      caseModel: c,
      discrepancy: verificationResult.discrepancyRecord,
    };
  }

  private transitionStatus(
    caseModel: HarnessCaseModel,
    nextStatus: CaseStatus,
    action: string,
    actor: string,
    details?: Record<string, unknown>
  ): void {
    const prevStatus = caseModel.status;
    caseModel.status = nextStatus;
    caseModel.updated_at = new Date().toISOString();
    this.recordAudit(caseModel.case_id, nextStatus, action, actor, details, prevStatus);
  }

  private recordAudit(
    caseId: string,
    toStatus: CaseStatus,
    action: string,
    actor: string,
    details?: Record<string, unknown> | string,
    fromStatus?: CaseStatus
  ): void {
    const events = this.auditTrails.get(caseId) || [];
    const event: CaseAuditEvent = {
      event_id: `AUD-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      case_id: caseId,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }),
      from_status: fromStatus,
      to_status: toStatus,
      action,
      actor,
      details,
    };
    events.push(event);
    this.auditTrails.set(caseId, events);
  }
}

// Export singleton instance for app-wide lifecycle management
export const stockTraceEngine = new StockTraceCaseEngine();
